import {PrismaClient,Role,TaskStatus,Priority} from '@prisma/client'; import bcrypt from 'bcryptjs';
const p=new PrismaClient();
async function main(){await p.activity.deleteMany();await p.notification.deleteMany();await p.task.deleteMany();await p.project.deleteMany();await p.client.deleteMany();await p.refreshToken.deleteMany();await p.user.deleteMany();const pass=await bcrypt.hash('Password123!',12);const [admin,pm1,pm2,d1,d2,d3,d4]=await Promise.all([
 p.user.create({data:{name:'Aarav Admin',email:'admin@velozity.local',passwordHash:pass,role:Role.ADMIN}}),p.user.create({data:{name:'Ravi PM',email:'pm1@velozity.local',passwordHash:pass,role:Role.PM}}),p.user.create({data:{name:'Meera PM',email:'pm2@velozity.local',passwordHash:pass,role:Role.PM}}),
 ...['Dev One','Dev Two','Dev Three','Dev Four'].map((name,i)=>p.user.create({data:{name,email:`dev${i+1}@velozity.local`,passwordHash:pass,role:Role.DEVELOPER}}))]);
const clients=await Promise.all(['Acme Health','Northstar Retail','Greenfield NGO'].map((name,i)=>p.client.create({data:{name,email:`client${i+1}@example.com`}})));
const creators=[admin,pm1,pm2];const devs=[d1,d2,d3,d4];
for(let pi=0;pi<3;pi++){const pr=await p.project.create({data:{name:['Acme Portal','Northstar Commerce','Greenfield Learning'][pi],description:'Client delivery project seeded for assessment.',creatorId:creators[pi].id,clientId:clients[pi].id}});for(let ti=0;ti<6;ti++){const due=new Date();due.setDate(due.getDate()+(ti<2?-2:ti+1));const status=[TaskStatus.TODO,TaskStatus.IN_PROGRESS,TaskStatus.IN_REVIEW,TaskStatus.DONE,ti<2?TaskStatus.OVERDUE:TaskStatus.IN_PROGRESS,TaskStatus.TODO][ti];const t=await p.task.create({data:{projectId:pr.id,title:`${pr.name} Task ${ti+1}`,description:'Seeded task for demonstrating role filtering and activity.',developerId:devs[(pi+ti)%4].id,status,priority:[Priority.CRITICAL,Priority.HIGH,Priority.MEDIUM,Priority.LOW,Priority.HIGH,Priority.MEDIUM][ti],dueDate:due}});await p.activity.create({data:{type:'STATUS_CHANGED',message:`${creators[pi].name} moved Task #${t.id} from TODO → ${status}`,fromStatus:TaskStatus.TODO,toStatus:status,taskId:t.id,projectId:pr.id,userId:creators[pi].id,createdAt:new Date(Date.now()-((ti+1)*3600000))}});if(ti===0)await p.notification.create({data:{userId:t.developerId,title:'New task assigned',message:`You were assigned ${t.title}`}})}}
console.log('Seed complete. Demo password: Password123!')}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>p.$disconnect());
