import {Router} from 'express'; import {z} from 'zod'; import {Role,TaskStatus,Priority} from '@prisma/client'; import {prisma} from '../lib/prisma.js'; import {emitProject,emitToUser,emitGlobal} from '../lib/realtime.js'; import {requireAuth} from '../middleware/auth.js'; import {canViewTask} from '../services/access.js';
export const taskRouter=Router(); taskRouter.use(requireAuth);
const query=z.object({status:z.nativeEnum(TaskStatus).optional(),priority:z.nativeEnum(Priority).optional(),from:z.coerce.date().optional(),to:z.coerce.date().optional()});
taskRouter.get('/',async(req,res,next)=>{try{const q=query.parse(req.query),u=req.user!;const where:any={};if(u.role===Role.DEVELOPER)where.developerId=u.id;else if(u.role===Role.PM)where.project={creatorId:u.id};if(q.status)where.status=q.status;if(q.priority)where.priority=q.priority;if(q.from||q.to)where.dueDate={...(q.from?{gte:q.from}:{}),...(q.to?{lte:q.to}:{})};const tasks=await prisma.task.findMany({where,include:{project:{select:{id:true,name:true}},developer:{select:{id:true,name:true}}},orderBy:[{priority:'desc'},{dueDate:'asc'}]});res.json({tasks})}catch(e){next(e)}});
const status=z.object({status:z.nativeEnum(TaskStatus)});
taskRouter.patch('/:id/status',async(req,res,next)=>{try{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({error:{code:'INVALID_ID',message:'Invalid task id'}});if(!(await canViewTask(req.user!.id,req.user!.role,id)))return res.status(403).json({error:{code:'FORBIDDEN',message:'You cannot update this task'}});const b=status.parse(req.body);const actor=await prisma.user.findUnique({where:{id:req.user!.id},select:{name:true}}); const old=await prisma.task.findUnique({where:{id},include:{project:true,developer:true}});if(!old)return res.status(404).json({error:{code:'NOT_FOUND',message:'Task not found'}});if(req.user!.role===Role.DEVELOPER && b.status===TaskStatus.OVERDUE)return res.status(400).json({error:{code:'INVALID_STATUS',message:'Developers cannot set Overdue manually'}});const t=await prisma.task.update({where:{id},data:{status:b.status}});const msg=`${actor?.name ?? 'User'} moved Task #${t.id} from ${old.status} → ${t.status}`;const a=await prisma.activity.create({data:{type:'STATUS_CHANGED',message:msg,fromStatus:old.status,toStatus:t.status,taskId:t.id,projectId:t.projectId,userId:req.user!.id}});if(b.status===TaskStatus.IN_REVIEW && old.developerId){await prisma.notification.create({data:{userId:old.project.creatorId,title:'Task in review',message:`Task #${t.id} (${t.title}) was moved to In Review.`}})};emitProject(t.projectId,'activity:new',{activity:a}); emitGlobal('activity:new',{activity:a}); emitToUser(old.project.creatorId,'notification:new',{message:`Task #${t.id} moved to In Review`}); res.json({task:t,activity:a})}catch(e){next(e)}});

taskRouter.patch('/:id',async(req,res,next)=>{try{const id=Number(req.params.id);if(!(await canViewTask(req.user!.id,req.user!.role,id))||req.user!.role===Role.DEVELOPER)return res.status(403).json({error:{code:'FORBIDDEN',message:'Only project managers/admins can manage task details'}});const b=z.object({title:z.string().min(2).max(150).optional(),description:z.string().max(2000).optional(),developerId:z.string().optional(),priority:z.nativeEnum(Priority).optional(),dueDate:z.coerce.date().optional()}).parse(req.body);if(b.developerId){const d=await prisma.user.findFirst({where:{id:b.developerId,role:Role.DEVELOPER}});if(!d)return res.status(400).json({error:{code:'INVALID_DEVELOPER',message:'Assigned user must be a developer'}})}const t=await prisma.task.update({where:{id},data:b});res.json({task:t})}catch(e){next(e)}});
export default taskRouter;
